export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_ORDERS = "FETCH_USER_ORDERS";

///// SERVER ACTIONS ///////
export const CHECK_SERVER_STATUS = "CHECK_SERVER_STATUS";

export const LAST_ORDERS_GLOBAL = "LAST_ORDERS_GLOBAL";
